[package]
name = "licensed"
version = "0.1.0"
authors = ["Vasily Fedorov <vasily.fedorov@arsysop.ru>"]
edition = "2021"

[dependencies]
anyhow = "1.0.102"
dioxus = "0.7.5"
dioxus-core = "0.7.4"
dioxus-signals = "0.7.4"
dioxus-web = "0.7.5"
ip_tools = { path = "../ip_tools" }
serde = { version = "1.0.228", features = ["derive"] }
tokio = { version = "1.52.1", features = ["net", "sync"] }
toml = "1.1.2"

[features]
desktop = ["dioxus/desktop"]
